RPI4-Configurer

diff --git a/archrpi4-config b/archrpi4-config
--- a/archrpi4-config
+++ b/archrpi4-config
@@ -11,13 +11,13 @@ rm /tmp/hosttemp.sh* 2> /dev/null
 LOCALESTEMP=/tmp/localestemp.sh.$$
 HOSTTEMP=/tmp/hosttemp.sh.$$
 
-XRDPTOGGLE=0
+SUDOUSER=""
 
 function cleanup { rm $LOCALESTEMP; $HOSTTEMP; exit; }
 
 trap cleanup; SIGHUP SIGINT SIGTERM
 
-function core { clear; cover; sleep 1s; verify; packages; hostnamer; localer; cockpit; graphical; remote; kvm; ohmyzsh; software; finisher; }
+function core { clear; cover; sleep 1s; verify; packages; hostnamer; localer; newuser; swapper; graphical; aur; ohmyzsh; software; finisher;}
 
 function cover {
 	echo '          					    ``...`                                                    '
@@ -82,47 +82,36 @@ function whichverify() {
 }
 
 function verify {
-
     ARCH=$(uname -m)
     OPERATING=$(uname -o)
-	ORACLE=$(cat /etc/os-release | head -n 1 | cut -d "=" -f2)
 	SELECTOR=""
+	PI="$(cat /sys/firmware/devicetree/base)"
 
 	if [ "$OPERATING" != "GNU/Linux" ]; then
 		clear
 		echo 'ERROR: Your Operating System is not GNU/Linux, exiting'
 		exit 1
 	fi
-	
-	if [ -d /sys/firmware/efi ]; then
-		echo "ready" &> /dev/null
-	else
-		clear
-		echo "ERROR: This scripts only works in UEFI/EFI systems, consider change your PC or check your BIOS"
-		exit 1
-	fi
 
-
-    if [[ "$ORACLE" =~ \"Oracle.* ]]; then
-		echo "ready" &> /dev/null
-	else
-		echo "ERROR: This script is only intended to run on Oracle Linux"
+    if [ "$ARCH" != "aarch64" ]; then
+        echo "ERROR: This script is only intended to run on aarch64 Devices."
         exit 1
     fi
 
-	
-    if [ "$ARCH" != "x86_64" ]; then
-        echo "ERROR: This script is only intended to run on x86_64 PCs."
+    if [[ "$PI" =~ ^Raspberry[[:space:]]Pi[[:space:]]4.* ]]; then
+        echo "ready" &> /dev/null
+	else
+		echo "ERROR: This script is only intended to run on Raspberry Pi 4 Devices."
         exit 1
     fi
 
-    SELECTOR="dnf"
+    SELECTOR="pacman"
 	whichverify "$SELECTOR"
 	local res=$?
 
 	if [ $res -eq 1 ]; then
 		clear
-		echo "ERROR: DNF is not available in this system, this system isn't Oracle Linux?"
+		echo "ERROR: Arch Linux pacman is not available in this system, this system isn't Arch Linux?"
 		exit 1
 	fi
 
@@ -134,8 +123,31 @@ function verify {
 		exit 1
 	fi
 
-    echo "Updating Oracle Linux Repositories... Please Wait"
-    dnf update --assumeyes &> /dev/null
+	echo "Populating Arch ARM Keys.."
+
+	pacman-key --init
+	pacman-key --populate archlinuxarm
+
+    echo "Updating Arch ARM Repositories..."
+
+    pacman -Sy &> /dev/null
+
+    SELECTOR="lsb_release"
+	whichverify "$SELECTOR"
+	local res=$?
+
+	if [ $res -eq 1 ]; then
+		echo "lsb_release is not available in this system, installing"
+		pacman -S lsb-release --noconfirm &> /dev/null
+	fi
+
+	IS_ARCH=$(lsb_release -is)
+
+	if [ "$IS_ARCH" != "Arch" ]; then
+		clear
+		echo "ERROR: Your Operating System is not Arch Linux, exiting"
+		exit 1
+	fi
 
 	SELECTOR="dialog"
 	whichverify "$SELECTOR"
@@ -143,9 +155,10 @@ function verify {
 
 	if [ $res -eq 1 ]; then
 		echo "dialog is not available in this system, installing"
-		dnf install dialog --assumeyes &> /dev/null
+		pacman -S dialog --noconfirm &> /dev/null
 	fi
-	
+
+	pacman -S ncurses --noconfirm &> /dev/null
 
 	echo "All dependencies is ok!"
 
@@ -164,9 +177,15 @@ function verify {
 function packages {
 	clear
 
-	echo -e "=============== CORE PACKAGES =============== \n" 
+	echo -e "=============== SYSTEM UPDATE AND INSTALL CORE PACKAGES =============== \n" 
 
-	dnf -y install net-tools wget nano zsh
+		systemctl enable sshd &> /dev/null
+		systemctl start sshd &> /dev/null
+
+		pacman -Syyu --noconfirm 
+		pacman -S sudo git wget rsync networkmanager f2fs-tools neofetch \
+		screen unrar p7zip vim zsh --noconfirm 
+		
 
 	echo -e "=============== OK =============== \n" 
 	read -r -p "Press Enter to continue..."
@@ -174,18 +193,20 @@ function packages {
 }
 
 function hostnamer {
+	
 
 	clear
 	dialog --title "Hostname" \
     --backtitle "036 Creative Studios" \
-    --inputbox "Please write your hostname (ex: A036-oracle)" 8 80 2>"$HOSTTEMP"
+    --inputbox "Please write your hostname (ex: A036-rpi4)" 8 80 2>"$HOSTTEMP"
 
     RESPONSE=$?
     DATA=$(<$HOSTTEMP)
 
     case $RESPONSE in
     0) 
-		hostnamectl set-hostname "${DATA}" 
+		echo "${DATA}" > /etc/hostname
+		echo "127.0.1.1        ${DATA}" >> /etc/hosts
 		return;;
     1) 
         clear; exit 0  
@@ -194,232 +215,190 @@ function hostnamer {
         clear; exit 0
         return;;
     esac
-	
 }
 
 function localer {
 
 	clear
 	dialog --msgbox "America/Guayaquil is the timezone by default, if you want to change, here is the command\n\n \
-		timedatectl set-timezone REGION/CITY" 9 50
+		ln -sf /usr/share/zoneinfo/REGION/CITY /etc/localtime" 9 50
 
-	timedatectl set-timezone America/Guayaquil
+	ln -sf /usr/share/zoneinfo/America/Guayaquil /etc/localtime
+	hwclock --systohc
 
 	dialog --clear --backtitle "036 Creative Studios" \
 		--title "Locale" \
-		--menu "Choose your keyboard layout" 12 50 4 \
-		Spanish "es" \
-		English "us" 2>"${LOCALESTEMP}"
+		--menu "Choose your locale, if you want to change to other locales, check the README of the Github of this project" 12 50 4 \
+		Spanish "es_ES" \
+		English "en_US" 2>"${LOCALESTEMP}"
 
 		menuitem=$(<"${LOCALESTEMP}")
 
 		case $menuitem in
 			Spanish) 
 				clear
-				localectl set-keymap es
+				sed -i 's/^#es_ES.UTF-8 UTF-8/es_ES.UTF-8 UTF-8/' /etc/locale.gen &> /dev/null
+				locale-gen
+				echo 'LANG="es_ES.UTF-8"' > /etc/locale.conf
+				echo 'LC_TIME="es_ES.UTF-8"' >> /etc/locale.conf
+				echo 'LANGUAGE="es_EC:es_ES:es"' >> /etc/locale.conf
 				return;;
 			English) 
 				clear
-				localectl set-keymap us
+				sed -i 's/^#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen &> /dev/null
+				locale-gen
+				echo 'LANG="en_US.UTF-8"' > /etc/locale.conf
+				echo 'LC_TIME="en_US.UTF-8"' >> /etc/locale.conf
+				echo 'LANGUAGE="es_US:en"' >> /etc/locale.conf
 				return;;
 			*) clear; exit 0;;
 		esac
 }
 
-function cockpit {
+function newuser {
 
 	clear
-	echo -e "=============== COCKPIT SERVICE (IP:9090) =============== \n" 
+	echo -e "=============== ADD A USER TO A SUDO GROUP =============== \n" 
 	
-	systemctl enable --now cockpit.socket
-	systemctl start cockpit.socket
+	read -r -p "Write your new user: " SUDOUSER
+	useradd --create-home "$SUDOUSER"
+	passwd "$SUDOUSER"
+	usermod -aG wheel "$SUDOUSER"
+	sed -i 's/^#.*%wheel ALL=(ALL) ALL$/%wheel ALL=(ALL) ALL/' /etc/sudoers &> /dev/null
 
 	echo " "
 	echo -e "=============== OK =============== \n" 
 	read -r -p "Press Enter to continue..."
+}
 
+function swapper {
+
+	clear
+	echo -e "=============== SWAPPING =============== \n" 
+
+	dd if=/dev/zero of=/swapfile bs=1M count=1024 status=progress
+	chmod 600 /swapfile
+	mkswap /swapfile
+	swapon /swapfile
+	echo "swapfile none swap defaults 0 0" >> /etc/fstab
+	echo "vm.swappiness=1" >> /etc/sysctl.d/99-sysctl.conf
+
+	
+	echo " "
+	echo -e "=============== OK =============== \n" 
+	read -r -p "Press Enter to continue..."
 }
 
 function graphical {
 
-	LISTHOME=""
+	clear
+	dialog --clear --title "Graphical Environment" \
+	--backtitle "036 Creative Studios" \
+	--menu "Choose a GUI, these are the common used, this script recommends XFCE" 15 50 4 \
+			XFCE "Xfce Desktop Environment" \
+			GNOME "GNOME Desktop Environment" \
+			KDE "KDE Desktop Environment" \
+			XORG "Minimal xorg Desktop" \
 
-	dialog --title "Graphical" --backtitle "036 Creative Studios" \
-		--yesno "Install XFCE as Desktop Environment?" 7 60
+			NOGUI "No install GUI" 2>"${GRAPHICALTEMP}"
 
-	response=$?
+	menuitem=$(<"${GRAPHICALTEMP}")
+
+		case $menuitem in
+			XFCE) 
+
+				clear
+				echo -e "=============== XFCE =============== \n" 
 	
-	if [ $response = 0 ]; then
+				pacman -S xorg-server xf86-video-fbturbo-git xorg-xinit --noconfirm
+				pacman -S xfce4 gdm xfce4-goodies ttf-ubuntu-font-family gtk-engines gtk-engine-murrine \
+					gnome-themes-standard xdg-user-dirs ttf-dejavu gvfs xfce4-notifyd network-manager-applet volumeicon --noconfirm
+				systemctl enable gdm
 
-	XRDPTOGGLE=1
+				touch /HOME/"$SUDOUSER"/.xinitrc
+				echo "export XAUTHORITY=${HOME}/.Xauthority" > /HOME/"$SUDOUSER"/.xinitrc
+				echo "exec dbus-run-session -- startxfce4" >> /HOME/"$SUDOUSER"/.xinitrc	
 
-		clear
-		echo -e "=============== EPEL & XFCE =============== \n" 
-		
-		dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm --assumeyes 
-		dnf update --assumeyes 
-		dnf groupinstall "base-x" --assumeyes 
-		dnf groupinstall "xfce" --assumeyes 
-		dnf install xfce4-whiskermenu-plugin --assumeyes 
-		touch .xinitrc
-		echo "xfce4-session" > .xinitrc
+				echo " "
+				echo -e "=============== OK =============== \n" 
+				read -r -p "Press Enter to continue..."
+				return;;
 
-		LISTHOME=$(ls /home)
+			GNOME) 
 
-		for HOME in $LISTHOME; do
-			touch /home/"$HOME"/.xinitrc
-			echo "xfce4-session" > /home/"$HOME"/.xinitrc
-			chown "$HOME" /home/"$HOME"/.xinitrc
-		done
+				clear
+				echo -e "=============== GNOME =============== \n" 
+				pacman -S xorg-server xf86-video-fbturbo-git xorg-xinit --noconfirm
+				pacman -S gnome gdm gnome-themes-standard network-manager-applet --noconfirm
+				systemctl enable gdm
 
-		echo " "
-		echo -e "=============== OK =============== \n" 
-		read -r -p "Press Enter to continue..."
+				echo " "
+				echo -e "=============== OK =============== \n" 
+				read -r -p "Press Enter to continue..."
+				return;;
 
-	else
+			KDE) 
 
-		clear
-		echo -e "=============== EPEL =============== \n" 
-		
-		dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm --assumeyes 
-	
-		echo " "
-		echo -e "=============== OK =============== \n" 
-		read -r -p "Press Enter to continue..."
-		return
-	fi
+				clear
+				echo -e "=============== KDE =============== \n" 
+				pacman -S xorg-server xf86-video-fbturbo-git xorg-xinit --noconfirm
+				pacman -S plasma plasma-wayland-session kde-applications network-manager-applet \
+					network-manager-applet volumeicon --noconfirm
+				systemctl enable sddm.service
+
+				echo " "
+				echo -e "=============== OK =============== \n" 
+				read -r -p "Press Enter to continue..."
+				return;;
+
+			XORG) 
+
+				clear
+				echo -e "=============== XORG ONLY =============== \n" 
+				pacman -S xorg-server xf86-video-fbturbo-git xorg-xinit --noconfirm
+
+				echo " "
+				echo -e "=============== OK =============== \n" 
+				read -r -p "Press Enter to continue..."
+				return;;
+
+			NOGUI) 
+				return;;
+
+			*) clear; exit 0;;
+		esac
+
+			clear
+			echo -e "=============== BLUETOOTH AND SOUND =============== \n" 
+
+			pacman -S  alsa-utils alsa-firmware alsa-lib alsa-plugins pulseaudio-alsa \
+				pulseaudio-bluetooth bluez-utils libmm-glib modemmanager blueman --noconfirm
+
+			sudo systemctl enable ModemManager
+			sudo systemctl enable bluetooth
+			sudo systemctl start ModemManager
+			sudo systemctl start bluetooth
+
+			echo " "
+			echo -e "=============== OK =============== \n" 
+			read -r -p "Press Enter to continue..."
 
 }
 
-function drivers {
+function aur {
 
 	clear
+	echo -e "=============== AUR (YAY ASKS YOU YOUR PASSWORD, PAY ATTENTION) ===============  \n" 
 
-	dialog --title "VMware" --backtitle "036 Creative Studios" \
-		--yesno "This is a VMware Guest" 8 60
+	pacman -S --needed base-devel fakeroot packer go --noconfirm
 
-	clear
-	response=$?
-
-	if [ $response = 0 ]; then
-
-	clear
-	dnf install open-vm-tools open-vm-tools-desktop --assumeyes 
-
-	elif [ $response -eq 1 ]; then
-		clear
-		return
-	else
-		clear
-		return
-	fi
-
-}
-
-function remote {
-
-	clear
-
-	dialog --title "SSH" --backtitle "036 Creative Studios" \
-		--yesno "Permit Root Login?" 8 60
-
-	response=$?
-
-	if [ $response = 0 ]; then
-
-		clear
-
-		echo -e "=============== SSH: PERMIT ROOT LOGIN ===============  \n" 
-
-		sed -i 's/^#PermitRootLogin\s.*$/PermitRootLogin Yes/' \
-			/etc/ssh/sshd_config &> /dev/null
-		systemctl enable sshd
-		systemctl restart sshd
-
-		echo " "
-		echo -e "=============== OK =============== \n" 
-		read -r -p "Press Enter to continue..."
-
-	fi
-
-	clear
-
-	if [ $XRDPTOGGLE -eq 1 ]; then
-
-		echo -e "=============== XRDP ===============  \n" 
-
-		LISTHOME=""
-
-		dnf install xrdp --assumeyes 
-
-		LISTHOME=$(ls /home)
-
-		for HOME in $LISTHOME; do
-			touch /home/"$HOME"/.Xclients
-			echo "xfce4-session" > /home/"$HOME"/.Xclients
-			chmod a+x /home/"$HOME"/.Xclients
-			chown "$HOME" /home/"$HOME"/.Xclients
-		done
-
-		systemctl enable xrdp
-		systemctl enable xrdp-sesman
-		systemctl start xrdp
-		systemctl start xrdp-sesman
-		firewall-cmd --permanent --add-port=3389/tcp 
-		firewall-cmd --reload
-		chcon --type=bin_t /usr/sbin/xrdp
-		chcon --type=bin_t /usr/sbin/xrdp-sesman
-
-		echo " "
-		echo -e "=============== OK =============== \n" 
-		read -r -p "Press Enter to continue..."
-	
-	fi
-
-}
-
-function kvm {
-
-	dialog --title "KVM" --backtitle "036 Creative Studios" \
-		--yesno "Install Oracle Linux KVM Suite?" 8 60
-
-	response=$?
-
-	if [ $response = 0 ]; then
-
-	clear
-
-	echo -e "=============== KVM ===============  \n" 
-
-	dnf config-manager --enable ol8_appstream ol8_kvm_appstream ol8_developer_EPEL
-	dnf module install virt --assumeyes 
-	dnf install virt-install virt-viewer virt-manager edk2-ovmf virt-v2v cockpit-machines --assumeyes
-	virt-host-validate qemu
-	systemctl enable libvirtd
-	systemctl start libvirtd
-	dnf install dnf-plugins-core --assumeyes 
-	dnf config-manager --add-repo https://www.kraxel.org/repos/firmware.repo
-	dnf install edk2.git-ovmf-x64 --assumeyes 
-
-	echo "nvram = [" >> /etc/libvirt/qemu.conf
-	echo "	\"/usr/edk.git/OVMF_CODE.fd:/usr/edk.git/OVMF_VARS.fd\"" >> /etc/libvirt/qemu.conf
-	echo "]" >> /etc/libvirt/qemu.conf
-
-	systemctl restart libvirtd
-	systemctl enable serial-getty@ttyS0.service
-	systemctl start serial-getty@ttyS0.service
+	sudo -u "$SUDOUSER" bash -c 'cd; git clone https://aur.archlinux.org/yay-bin.git'
+	sudo -u "$SUDOUSER" bash -c 'cd; cd yay-bin; makepkg -si'
+	sudo -u "$SUDOUSER" bash -c 'cd; rm -rf yay-bin'
 
 	echo " "
 	echo -e "=============== OK =============== \n" 
 	read -r -p "Press Enter to continue..."
-
-	elif [ $response -eq 1 ]; then
-		clear
-		return
-	else
-		clear
-		return
-	fi
 
 }
 
@@ -428,23 +407,19 @@ function ohmyzsh {
 	clear
 	echo -e "=============== OMZ =============== \n" 
 
-	LISTHOME=$(ls /home)
+	touch /home/"$SUDOUSER"/omz.sh
 
-	for HOME in $LISTHOME; do
+	echo '#!/bin/bash' > /home/"$SUDOUSER"/omz.sh
+	echo 'sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"' >> /home/"$SUDOUSER"/omz.sh
+	echo 'sed -i -e "s/ZSH_THEME=.*/ZSH_THEME=\"pmcgee\"/" .zshrc' >> /home/"$SUDOUSER"/omz.sh
+	echo 'sed -i -e "/^source $ZSH.*/i ZSH_DISABLE_COMPFIX=true" .zshrc' >> /home/"$SUDOUSER"/omz.sh
+	echo 'sudo ln -s "$HOME"/.zshrc /root/.zshrc' >> /home/"$SUDOUSER"/omz.sh
+	echo 'sudo ln -s "$HOME"/.oh-my-zsh /root/.oh-my-zsh' >> /home/"$SUDOUSER"/omz.sh
+	echo 'git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting' >> /home/"$SUDOUSER"/omz.sh
+	echo 'git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions' >> /home/"$SUDOUSER"/omz.sh
+	echo 'sed -i -e "s/plugins=(.*/plugins=(git zsh-syntax-highlighting zsh-autosuggestions)/" .zshrc' >> /home/"$SUDOUSER"/omz.sh
 
-		echo '#!/bin/bash' > /home/"$HOME"/omz.sh
-		echo 'sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"' >> /home/"$HOME"/omz.sh
-		echo 'sed -i -e "s/ZSH_THEME=.*/ZSH_THEME=\"pmcgee\"/" .zshrc' >> /home/"$HOME"/omz.sh
-		echo 'sed -i -e "/^source $ZSH.*/i ZSH_DISABLE_COMPFIX=true" .zshrc' >> /home/"$HOME"/omz.sh
-		echo 'sudo ln -s "$HOME"/.zshrc /root/.zshrc' >> /home/"$HOME"/omz.sh
-		echo 'sudo ln -s "$HOME"/.oh-my-zsh /root/.oh-my-zsh' >> /home/"$HOME"/omz.sh
-		echo 'git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting' >> /home/"$HOME"/omz.sh
-		echo 'git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions' >> /home/"$HOME"/omz.sh
-		echo 'sed -i -e "s/plugins=(.*/plugins=(git zsh-syntax-highlighting zsh-autosuggestions)/" .zshrc' >> /home/"$HOME"/omz.sh
-
-		chown "$HOME" /home/"$HOME"/omz.sh
-
-	done
+	chown "$SUDOUSER" /home/"$SUDOUSER"/omz.sh
 
 	echo "We create a script called omz.sh in your home directory, after reboot, use chmod +x at omz.sh"
 
@@ -456,18 +431,25 @@ function ohmyzsh {
 
 function software {
 
-	dialog --title "More Sofware!!" --backtitle "036 Creative Studios" \
+	systemctl mask lvm2-monitor
+
+		dialog --title "More Sofware!!" --backtitle "036 Creative Studios" \
 		--yesno "This script has a little pack of software, Do you like it?\n \
 			-> baobab \n \
 			-> ntfs-3g \n \
-			-> gparted \n \
-			-> nautilus \n \
-			-> gedit \n \
-			-> tar \n \
-			-> yum-utils \n \
-			-> numix-gtk-theme \n \
+			-> exfatprogs \n \
+			-> exfat-utils \n \
+			-> xrdp \n \
+			-> xarchiver \n \
+			-> xorgxrdp \n \
+			-> xorgxrdp \n \
+			-> visual-studio-code \n \
+			-> rpi-eeprom-git \n \
+			-> rpi-imager \n \
+			-> box64 \n \
+			-> numix-gtk-theme-git\n \
 			-> numix-icon-theme \n \
-			-> numix-icon-theme-circle" 20 65
+			-> preload " 26 65
 	clear
 	response=$?
 
@@ -476,14 +458,26 @@ function software {
 	clear
 	echo -e "=============== SOFTWARE =============== \n" 
 
-	dnf install baobab ntfs-3g gparted exfatprogs nautilus gedit tar yum-utils --assumeyes
+	touch /home/"$SUDOUSER"/software.sh
 
-	dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm --assumeyes
-	dnf install numix-gtk-theme --assumeyes
-	dnf install gnome-icon-theme --assumeyes
-	dnf install numix-icon-theme --assumeyes
-	dnf install numix-icon-theme-circle --assumeyes
-	dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm --assumeyes
+	echo allowed_users=anybody > /etc/X11/Xwrapper.config
+
+	echo '!#/bin/bash' > /home/"$SUDOUSER"/software.sh
+	echo 'yay -S baobab ntfs-3g exfatprogs exfat-utils \' >> /home/"$SUDOUSER"/software.sh
+	echo 'xarchiver gparted xrdp \' >> /home/"$SUDOUSER"/software.sh
+	echo 'xorgxrdp pi-bluetooth visual-studio-code-bin preload \' >> /home/"$SUDOUSER"/software.sh
+	echo 'rpi-eeprom-git rpi-imager box64 \' >> /home/"$SUDOUSER"/software.sh
+	echo 'brave-bin exe-thumbnailer github-desktop-bin gobject-introspection libdbusmenu-gtk2 \' >> /home/"$SUDOUSER"/software.sh
+	echo 'libdbusmenu-glib libdbusmenu-gtk3 appmenu-gtk-module numix-gtk-theme \' >> /home/"$SUDOUSER"/software.sh
+	echo 'numix-icon-theme-git numix-circle-icon-theme-git' >> /home/"$SUDOUSER"/software.sh
+
+	echo 'systemctl enable xrdp' >> /home/"$SUDOUSER"/software.sh
+	echo 'systemctl enable xrdp-sesman' >> /home/"$SUDOUSER"/software.sh
+	echo 'systemctl enable preload' >> /home/"$SUDOUSER"/software.sh
+		
+	chown "$SUDOUSER" /home/"$SUDOUSER"/software.sh
+
+	echo "We create a script called software.sh in your home directory, after reboot, use chmod +x at software.sh"
 
 	echo " "
 	echo -e "=============== OK =============== \n" 
@@ -495,19 +489,18 @@ function software {
 		return
 	else
 		clear
-		return
+		exit 0
 	fi
-
 }
+
 
 function finisher {
 
 	clear
-	dialog --msgbox 'READY!!!, Your Server is succesfully configured, if you have errors, please report at 036bootstrap in GitHub' 7 50
+	dialog --msgbox 'READY!!!, Your RPI4 is succesfully configured, if you have errors, please report at 036raspberry in GitHub' 7 50
 	clear
-	echo "Please reboot yout server to make changes"
+	echo "Please reboot your rpi4 to make changes"
 	exit 0
-
 }
 
 core
