Oracle Linux Raspberry Release

diff --git a/olrpi4-config b/olrpi4-config
--- a/olrpi4-config
+++ b/olrpi4-config
@@ -5,15 +5,20 @@ if [ "$(id -u)" -ne 0 ]; then
 	exit 1
 fi
 
-rm /tmp/diskmenutemp.sh* 2> /dev/null
+rm /tmp/localestemp.sh* 2> /dev/null
+rm /tmp/hosttemp.sh* 2> /dev/null
 	
-DISKMENUTEMP=/tmp/diskmenutemp.sh.$$
+LOCALESTEMP=/tmp/localestemp.sh.$$
+HOSTTEMP=/tmp/hosttemp.sh.$$
 
-function cleanup { rm $DISKMENUTEMP; $; exit; }
+XRDPTOGGLE=0
+SUDOUSER=""
+
+function cleanup { rm $LOCALESTEMP; $HOSTTEMP; exit; }
 
 trap cleanup; SIGHUP SIGINT SIGTERM
 
-function core { clear; cover; sleep 1s; verify; usbstat; diskmenu; }
+function core { clear; cover; sleep 1s; verify; packages; hostnamer; localer; cockpit; newuser; graphical; remote; kvm; ohmyzsh; software; finisher; }
 
 function cover {
 	echo '          					    ``...`                                                    '
@@ -68,16 +73,6 @@ function cover {
 	echo ':::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::'
 }
 
-function usbstat {
-
-	VERIFYUSB=$(find /dev/disk/by-id/ -name 'usb*' | sort -n | sed 's/^\/dev\/disk\/by-id\///')
-	if [ "$VERIFYUSB" == "" ]; then
-		clear
-		echo "ERROR: There's no USB drives connected in this PC, please connect your SD Card in a USB SD Card Reader"
-		exit 1
-	fi
-}
-
 function whichverify() {
 	stat=$(which "$1" 2>&1)
 	if [[ "$stat" =~ which:* ]]; then 
@@ -89,13 +84,47 @@ function whichverify() {
 
 function verify {
 
+    ARCH=$(uname -m)
     OPERATING=$(uname -o)
-
+	ORACLE=$(cat /etc/os-release | head -n 1 | cut -d "=" -f2)
+	PI="$(cat /sys/firmware/devicetree/base/model)"
 	SELECTOR=""
+
 
 	if [ "$OPERATING" != "GNU/Linux" ]; then
 		clear
 		echo 'ERROR: Your Operating System is not GNU/Linux, exiting'
+		exit 1
+	fi
+	
+
+    if [[ "$ORACLE" =~ \"Oracle.* ]]; then
+		echo "ready" &> /dev/null
+	else
+		echo "ERROR: This script is only intended to run on Oracle Linux"
+        exit 1
+    fi
+	
+    if [ "$ARCH" != "aarch64" ]; then
+        echo "ERROR: This script is only intended to run on x86_64 PCs."
+        exit 1
+    fi
+
+	if [[ "$PI" =~ ^Raspberry[[:space:]]Pi[[:space:]]4.* ]]; then
+        echo "ready" &> /dev/null
+	else
+		echo "ERROR: This script is only intended to run on Raspberry Pi 4 Devices."
+        exit 1
+    fi
+
+
+    SELECTOR="dnf"
+	whichverify "$SELECTOR"
+	local res=$?
+
+	if [ $res -eq 1 ]; then
+		clear
+		echo "ERROR: DNF is not available in this system, this system isn't Oracle Linux, please use Oracle Linux 8?"
 		exit 1
 	fi
 
@@ -107,41 +136,18 @@ function verify {
 		exit 1
 	fi
 
+    echo "Updating Oracle Linux Repositories... Please Wait"
+    dnf update --assumeyes &> /dev/null
+
 	SELECTOR="dialog"
 	whichverify "$SELECTOR"
 	local res=$?
 
 	if [ $res -eq 1 ]; then
-		echo "dialog is not available in this system, please install it"
-		exit 1
+		echo "dialog is not available in this system, installing"
+		dnf install dialog --assumeyes &> /dev/null
 	fi
 	
-	SELECTOR="parted"
-	whichverify "$SELECTOR"
-	local res=$?
-
-	if [ $res -eq 1 ]; then
-		echo "parted is not available in this system, please install it"
-		exit 1
-	fi
-	
-	SELECTOR="wget"
-	whichverify "$SELECTOR"
-	local res=$?
-
-	if [ $res -eq 1 ]; then
-		echo "wget is not available in this system, please install it"
-		exit 1
-	fi
-	
-	SELECTOR="bsdtar"
-	whichverify "$SELECTOR"
-	local res=$?
-
-	if [ $res -eq 1 ]; then
-		echo "bsdtar is not available in this system (libarchive), please install it"
-		exit 1
-	fi
 
 	echo "All dependencies is ok!"
 
@@ -157,152 +163,301 @@ function verify {
 
 }
 
-function diskmenu {
-
-	clear
-	usbstat
-
-	dialog --msgbox "ATTENTION!!! Your SD card would be listed as a USB device, ensure that your SD is empty and ready for format" 7 70
-
+function packages {
 	clear
 
-	DIRTYDEVS=()
-	BLOCK=()
+	echo -e "=============== CORE PACKAGES =============== \n" 
 
-	USBS=$(find /dev/disk/by-id/ -name 'usb*' | sort -n | sed 's/^\/dev\/disk\/by-id\///') # usb-USB3.0_high_speed_000000123AFF-0:0 ...
+	dnf install rsync sudo nano git net-tools wget nano e2fsprogs \
+		cockpit glibc-all-langpacks glibc-langpack-es -y
 
-	for DEVICE in $USBS; do
-		DIRTYDEVS[$COUNT]=$(readlink "/dev/disk/by-id/$DEVICE") # ../../sda ../../sda1 ... 
-		COUNT=$(( COUNT + 1 ))
-	done
-
-	for DEV in "${DIRTYDEVS[@]}"; do
-
-		ABSOLUTEPARTS=$(echo "$DEV" | sed 's/^\.\.\/\.\.\//\/dev\//' | sed '/.*sd[[:alpha:]]$/d') #/dev/sda1 /dev/sda2 ...
-
-		if [ "$ABSOLUTEPARTS" == "" ]; then
-			BLOCK[$BLOCKCOUNT]=$(echo "$DEV" | sed 's/^\.\.\/\.\.\///') #sda sdb 
-			BLOCKCOUNT=$(( BLOCKCOUNT + 1 ))
-		fi
-	done
-
-	COUNT=0
-	MODEL=0
-	DEVICE=0
-	ARGSUSB=()
-
-	for PART in "${BLOCK[@]}"; do
-		DEVICE="/dev/$PART"
-		BLOCKSTAT="${BLOCK[$COUNT]}"
-		SIZE=$(lsblk -no SIZE /dev/"$PART" | head -1 | sed s/..//)
-		MODEL="$(cat /sys/class/block/"$BLOCKSTAT"/device/model)" #KINGSTON 
-		ARGSUSB+=("$DEVICE" "$MODEL $SIZE")
-		COUNT=$(( COUNT + 1 ))
-	done
-
-	dialog --clear --backtitle "036 Creative Studios" --title "Format a Device" \
-		--menu "Choose a device"\
-		15 50 4 "${ARGSUSB[@]}" 2>"${DISKMENUTEMP}"
-
-	CHOICE=$(<"${DISKMENUTEMP}")
-
-	case $CHOICE in
-		"$CHOICE") diskformat "$CHOICE";;
-		*) clear;;
-	esac
+	echo -e "=============== OK =============== \n" 
+	read -r -p "Press Enter to continue..."
 
 }
 
-function diskformat() {
-	
-	if [ "$1" == "" ]; then
-		clear
-		exit 0
-	fi
-
-	dialog --title "DANGER ZONE!!!" --backtitle "036 Creative Studios" \
-		--yesno "This device will be format Continue? \n $1" 7 60
+function hostnamer {
 
 	clear
-	response=$?
+	dialog --title "Hostname" \
+    --backtitle "036 Creative Studios" \
+    --inputbox "Please write your hostname (ex: A036-oracle)" 8 80 2>"$HOSTTEMP"
 
-	if [ $response -eq 0 ]; then
+    RESPONSE=$?
+    DATA=$(<$HOSTTEMP)
+
+    case $RESPONSE in
+    0) 
+		hostnamectl set-hostname "${DATA}" 
+		return;;
+    1) 
+        clear; exit 0  
+        return;;
+    255) 
+        clear; exit 0
+        return;;
+    esac
 	
-		echo -e "=============== NEW PARTITION TABLE TO SD CARD =============== \n" 
-
-		parted --script "$1" \
-			mklabel msdos \
-			mkpart primary fat32 1MiB 200MiB \
-			set 1 boot on \
-			mkpart primary ext4 200MiB 100% \
-			print
-
-		echo " "
-		echo -e "=============== OK =============== \n" 
-		read -r -p "Press Enter to continue..."
-		clear
-
-		echo -e "=============== FORMAT/MOUNT ROOT AND BOOT FILESYSTEMS =============== \n" 
-
-		mkfs.ext4 "$1"2
-		mkfs.fat -F32 "$1"1
-
-		mkdir /mnt/boot 
-		mkdir /mnt/root
-		mount "$1"2 /mnt/root
-		mount "$1"1 /mnt/boot
-
-		echo " "
-		echo -e "=============== OK =============== \n" 
-		read -r -p "Press Enter to continue..."
-		clear
-
-		baseinstall
-
-	else
-		clear
-		exit 1
-	fi
-
 }
-function baseinstall {
 
-	echo -e "=============== INSTALL ROOT AND BOOT FILESYSTEMS, PLEASE WAIT  =============== \n" 
+function localer {
 
-	wget http://os.archlinuxarm.org/os/ArchLinuxARM-rpi-aarch64-latest.tar.gz -P /mnt/root/
-	bsdtar -xpf /mnt/root/ArchLinuxARM-rpi-aarch64-latest.tar.gz -C /mnt/root/
-	sync
-	rm /mnt/root/ArchLinuxARM-rpi-aarch64-latest.tar.gz
-	mv /mnt/root/boot/* /mnt/boot/
-	sed -i 's/mmcblk0/mmcblk1/g' /mnt/root/etc/fstab
-	sed -i 's/^#PermitRootLogin\s.*$/PermitRootLogin Yes/' \
-		/mnt/root/etc/ssh/sshd_config &> /dev/null
+	clear
+	dialog --msgbox "America/Guayaquil is the timezone by default, if you want to change, here is the command\n\n \
+		timedatectl set-timezone REGION/CITY" 9 50
 
-	wget https://raw.githubusercontent.com/victor7w7r/036raspberry/master/archrpi4-config -P /mnt/root/root/
-	chmod +x /mnt/root/root/archrpi4-config
+	timedatectl set-timezone America/Guayaquil
 
-	umount /mnt/boot 
-	umount /mnt/root 
-	rm -rf /mnt/boot 
-	rm -rf /mnt/root
+	dialog --clear --backtitle "036 Creative Studios" \
+		--title "Locale" \
+		--menu "Choose your keyboard layout and locale" 12 50 4 \
+		Spanish "es" \
+		English "us" 2>"${LOCALESTEMP}"
+
+		menuitem=$(<"${LOCALESTEMP}")
+
+		case $menuitem in
+			Spanish) 
+				clear
+				localectl set-keymap es
+				localectl set-locale LANG=es_ES.UTF-8
+				return;;
+			English) 
+				clear
+				localectl set-keymap us
+				localectl set-locale LANG=en_US.UTF-8
+				return;;
+			*) clear; exit 0;;
+		esac
+}
+
+function cockpit {
+
+	clear
+	echo -e "=============== COCKPIT SERVICE (IP:9090) =============== \n" 
+	
+	systemctl enable --now cockpit.socket
+	systemctl start cockpit.socket
 
 	echo " "
 	echo -e "=============== OK =============== \n" 
 	read -r -p "Press Enter to continue..."
+
+}
+
+function newuser {
+
+	clear
+	echo -e "=============== ADD A USER TO A SUDO GROUP =============== \n" 
+	
+	read -r -p "Write your new user: " SUDOUSER
+	adduser "$SUDOUSER"
+	passwd "$SUDOUSER"
+	usermod -aG wheel "$SUDOUSER"
+
+	echo " "
+	echo -e "=============== OK =============== \n" 
+	read -r -p "Press Enter to continue..."
+
+}
+
+function graphical {
+
+	dialog --title "Graphical" --backtitle "036 Creative Studios" \
+		--yesno "Install XFCE as Desktop Environment?" 7 60
+
+	response=$?
+	
+	if [ $response = 0 ]; then
+
+	XRDPTOGGLE=1
+
+		clear
+		echo -e "=============== EPEL & XFCE =============== \n" 
+		
+		dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm --assumeyes 
+		dnf update --assumeyes 
+		dnf groupinstall "base-x" --assumeyes 
+		dnf groupinstall "xfce" --assumeyes
+		dnf install xfce4-whiskermenu-plugin --assumeyes 
+		touch .xinitrc
+		echo "xfce4-session" > .xinitrc
+
+		touch /home/"$SUDOUSER"/.xinitrc
+		echo "xfce4-session" > /home/"$SUDOUSER"/.xinitrc
+		chown "$SUDOUSER" /home/"$SUDOUSER"/.xinitrc
+
+		echo " "
+		echo -e "=============== OK =============== \n" 
+		read -r -p "Press Enter to continue..."
+
+	else
+
+		clear
+		echo -e "=============== EPEL =============== \n" 
+		
+		dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm --assumeyes 
+	
+		echo " "
+		echo -e "=============== OK =============== \n" 
+		read -r -p "Press Enter to continue..."
+		return
+	fi
+
+}
+
+function remote {
+
 	clear
 
-	finisher
+	if [ $XRDPTOGGLE -eq 1 ]; then
+
+		echo -e "=============== XRDP ===============  \n" 
+
+		dnf install xrdp --assumeyes 
+	
+		touch /home/"$SUDOUSER"/.Xclients
+		echo "xfce4-session" > /home/"$SUDOUSER"/.Xclients
+		chmod a+x /home/"$SUDOUSER"/.Xclients
+		chown "$SUDOUSER" /home/"$SUDOUSER"/.Xclients
+
+		systemctl enable xrdp
+		systemctl enable xrdp-sesman
+		systemctl start xrdp
+		systemctl start xrdp-sesman
+		firewall-cmd --permanent --add-port=3389/tcp 
+		firewall-cmd --reload
+		chcon --type=bin_t /usr/sbin/xrdp
+		chcon --type=bin_t /usr/sbin/xrdp-sesman
+
+		echo " "
+		echo -e "=============== OK =============== \n" 
+		read -r -p "Press Enter to continue..."
+	
+	fi
+
+}
+
+function kvm {
+
+	dialog --title "KVM" --backtitle "036 Creative Studios" \
+		--yesno "Install Oracle Linux KVM Suite?" 8 60
+
+	response=$?
+
+	if [ $response = 0 ]; then
+
+	clear
+
+	echo -e "=============== KVM ===============  \n" 
+
+	dnf module install virt -Y
+	dnf install virt-install virt-viewer virt-manager cockpit-machines -y
+	virt-host-validate qemu
+	systemctl enable libvirtd
+	systemctl start libvirtd
+
+	echo " "
+	echo -e "=============== OK =============== \n" 
+	read -r -p "Press Enter to continue..."
+
+	elif [ $response -eq 1 ]; then
+		clear
+		return
+	else
+		clear
+		return
+	fi
+
+}
+
+function ohmyzsh {
+
+	clear
+	echo -e "=============== OMZ =============== \n" 
+
+
+	echo '#!/bin/bash' > /home/"$SUDOUSER"/omz.sh
+	echo 'sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"' >> /home/"$SUDOUSER"/omz.sh
+	echo 'sed -i -e "s/ZSH_THEME=.*/ZSH_THEME=\"pmcgee\"/" .zshrc' >> /home/"$SUDOUSER"/omz.sh
+	echo 'sed -i -e "/^source $ZSH.*/i ZSH_DISABLE_COMPFIX=true" .zshrc' >> /home/"$SUDOUSER"/omz.sh
+	echo 'sudo ln -s "$HOME"/.zshrc /root/.zshrc' >> /home/"$SUDOUSER"/omz.sh
+	echo 'sudo ln -s "$HOME"/.oh-my-zsh /root/.oh-my-zsh' >> /home/"$SUDOUSER"/omz.sh
+	echo 'git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting' >> /home/"$SUDOUSER"/omz.sh
+	echo 'git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions' >> /home/"$SUDOUSER"/omz.sh
+	echo 'sed -i -e "s/plugins=(.*/plugins=(git zsh-syntax-highlighting zsh-autosuggestions)/" .zshrc' >> /home/"$SUDOUSER"/omz.sh
+
+	chown "$SUDOUSER" /home/"$SUDOUSER"/omz.sh
+
+	echo "We create a script called omz.sh in your home directory, after reboot, use chmod +x at omz.sh"
+
+	echo " "
+	echo -e "=============== OK =============== \n" 
+	read -r -p "Press Enter to continue..."
+
+}
+
+function software {
+
+	systemctl disable packagekitd
+	dnf remove PackageKit --assumeyes
+	echo "enabled=0" >> /etc/yum/pluginconf.d/refresh-packagekit.conf
+
+	dialog --title "More Sofware!!" --backtitle "036 Creative Studios" \
+		--yesno "This script has a little pack of software, Do you like it?\n \
+			-> baobab \n \
+			-> ntfs-3g \n \
+			-> gparted \n \
+			-> nautilus \n \
+			-> gedit \n \
+			-> tar \n \
+			-> yum-utils \n \
+			-> numix-gtk-theme \n \
+			-> numix-icon-theme \n \
+			-> numix-icon-theme-circle" 20 65
+	clear
+	response=$?
+
+	if [ $response = 0 ]; then
+	
+	clear
+	echo -e "=============== SOFTWARE =============== \n" 
+
+	dnf install baobab ntfs-3g gparted exfatprogs nautilus gedit tar yum-utils --assumeyes
+
+	dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm --assumeyes
+	dnf install numix-gtk-theme --assumeyes
+	dnf install gnome-icon-theme --assumeyes
+	dnf install numix-icon-theme --assumeyes
+	dnf install numix-icon-theme-circle --assumeyes
+	dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm --assumeyes
+
+	echo " "
+	echo -e "=============== OK =============== \n" 
+	read -r -p "Press Enter to continue..."
+
+
+	elif [ $response -eq 1 ] || [ $response -eq 255 ]; then
+		clear
+		return
+	else
+		clear
+		return
+	fi
 
 }
 
 function finisher {
+
 	clear
-	dialog --msgbox "At the superuser home directory, we put a configurer script if you want" 8 60
-	dialog --msgbox 'READY!!!, Your SD was installed with Arch Linux ARM for Raspberry PI 4, login as root/root, if you have errors, please report at 036raspberry in GitHub' 10 60
+	dialog --msgbox 'READY!!!, Your RPI4 is succesfully configured, if you have errors, please report at 036raspberry in GitHub' 7 50
 	clear
+	echo "Please reboot yout server to make changes"
 	exit 0
+
 }
 
 core
 
-[ -f $DISKMENUTEMP ] && rm $DISKMENUTEMP
+[ -f $LOCALESTEMP ] && rm $LOCALESTEMP
+[ -f $HOSTTEMP ] && rm $HOSTTEMP
