All Configs

diff --git a/oraclelinux-config b/oraclelinux-config
--- a/oraclelinux-config
+++ b/oraclelinux-config
@@ -7,19 +7,17 @@ fi
 
 rm /tmp/localestemp.sh* 2> /dev/null
 rm /tmp/hosttemp.sh* 2> /dev/null
-rm /tmp/graphicaltemp.sh* 2> /dev/null
 	
 LOCALESTEMP=/tmp/localestemp.sh.$$
 HOSTTEMP=/tmp/hosttemp.sh.$$
-GRAPHICALTEMP=/tmp/graphicaltemp.sh.$$
 
-SUDOUSER=""
+XRDPTOGGLE=0
 
-function cleanup { rm $LOCALESTEMP; $HOSTTEMP; $GRAPHICALTEMP exit; }
+function cleanup { rm $LOCALESTEMP; $HOSTTEMP; exit; }
 
 trap cleanup; SIGHUP SIGINT SIGTERM
 
-function core { clear; cover; sleep 1s; verify; packages; newuser; graphical; ohmyzsh; software; finisher;}
+function core { clear; cover; sleep 1s; verify; packages; hostnamer; localer; cockpit; graphical; remote; kvm; ohmyzsh; software; finisher; }
 
 function cover {
 	echo '          					    ``...`                                                    '
@@ -76,8 +74,7 @@ function cover {
 
 function whichverify() {
 	stat=$(which "$1" 2>&1)
-
-	if [ "$stat" == "" ]; then
+	if [[ "$stat" =~ which:* ]]; then 
 		return 1
 	else
 		return 0
@@ -85,56 +82,47 @@ function whichverify() {
 }
 
 function verify {
+
     ARCH=$(uname -m)
     OPERATING=$(uname -o)
+	ORACLE=$(cat /etc/os-release | head -n 1 | cut -d "=" -f2)
 	SELECTOR=""
-	PI="$(cat /sys/firmware/devicetree/base/model)"
 
 	if [ "$OPERATING" != "GNU/Linux" ]; then
 		clear
 		echo 'ERROR: Your Operating System is not GNU/Linux, exiting'
 		exit 1
 	fi
-
-    if [ "$ARCH" != "aarch64" ]; then
-        echo "ERROR: This script is only intended to run on aarch64 Devices."
-        exit 1
-    fi
-
-    if [[ "$PI" =~ ^Raspberry[[:space:]]Pi[[:space:]]4.* ]]; then
-        echo "ready" &> /dev/null
+	
+	if [ -d /sys/firmware/efi ]; then
+		echo "ready" &> /dev/null
 	else
-		echo "ERROR: This script is only intended to run on Raspberry Pi 4 Devices."
+		clear
+		echo "ERROR: This scripts only works in UEFI/EFI systems, consider change your PC or check your BIOS"
+		exit 1
+	fi
+
+
+    if [[ "$ORACLE" =~ \"Oracle.* ]]; then
+		echo "ready" &> /dev/null
+	else
+		echo "ERROR: This script is only intended to run on Oracle Linux"
         exit 1
     fi
 
-    SELECTOR="apt"
+	
+    if [ "$ARCH" != "x86_64" ]; then
+        echo "ERROR: This script is only intended to run on x86_64 PCs."
+        exit 1
+    fi
+
+    SELECTOR="dnf"
 	whichverify "$SELECTOR"
 	local res=$?
 
 	if [ $res -eq 1 ]; then
 		clear
-		echo "ERROR: APT is not available in this system, this system isn't Debian?"
-		exit 1
-	fi
-
-    SELECTOR="raspi-config"
-	whichverify "$SELECTOR"
-	local res=$?
-
-	if [ $res -eq 1 ]; then
-		clear
-		echo "ERROR: This Debian disto doesn't have a raspi-config app, please use Raspberry Pi OS Lite, exiting"
-		exit 1
-	fi
-
-	SELECTOR="openbox-lxde-session"
-	whichverify "$SELECTOR"
-	local res=$?
-
-	if [ $res -eq 0 ]; then
-		clear
-		echo "ERROR: Ok, is Raspbery Pi OS, but this is not a Raspberry Pi OS Lite, exiting"
+		echo "ERROR: DNF is not available in this system, this system isn't Oracle Linux?"
 		exit 1
 	fi
 
@@ -146,26 +134,8 @@ function verify {
 		exit 1
 	fi
 
-    echo "Updating Debian repositories..."
-
-    apt update &> /dev/null
-
-    SELECTOR="lsb_release"
-	whichverify "$SELECTOR"
-	local res=$?
-
-	if [ $res -eq 1 ]; then
-		echo "lsb_release is not available in this system, installing"
-		apt install -y lsb-release -&> /dev/null
-	fi
-
-	IS_ARCH=$(lsb_release -is)
-
-	if [ "$IS_ARCH" != "Debian" ]; then
-		clear
-		echo "ERROR: Your Operating System is not Arch Linux, exiting"
-		exit 1
-	fi
+    echo "Updating Oracle Linux Repositories... Please Wait"
+    dnf update --assumeyes &> /dev/null
 
 	SELECTOR="dialog"
 	whichverify "$SELECTOR"
@@ -173,8 +143,9 @@ function verify {
 
 	if [ $res -eq 1 ]; then
 		echo "dialog is not available in this system, installing"
-		apt install -y dialog &> /dev/null
+		dnf install dialog --assumeyes &> /dev/null
 	fi
+	
 
 	echo "All dependencies is ok!"
 
@@ -193,97 +164,262 @@ function verify {
 function packages {
 	clear
 
-	sed -i 's/^#PermitRootLogin\s.*$/PermitRootLogin Yes/' \
-	/etc/ssh/sshd_config &> /dev/null
+	echo -e "=============== CORE PACKAGES =============== \n" 
 
-	echo -e "=============== SYSTEM UPDATE  =============== \n" 
+	dnf -y install net-tools wget nano zsh
 
-	apt upgrade -y
-		
 	echo -e "=============== OK =============== \n" 
 	read -r -p "Press Enter to continue..."
-
-	clear
-
-	echo -e "=============== ROOT PASSWORD FOR YOUR SYSTEM =============== \n" 
-
-	passwd
-
-	echo " "
-	echo -e "=============== OK =============== \n" 
-	read -r -p "Press Enter to continue..."
-	
-	clear
-
-	echo -e "=============== CHANGE TO A SID REPOSITORIES AND DIST UPGRADE =============== \n" 
-
-	mv /etc/apt/sources.list /etc/apt/sources.list.old
-	mv /etc/apt/sources.list.d /etc/apt/sources.list.d.old
-
-	echo "deb http://deb.debian.org/debian sid main contrib non-free" > /etc/apt/sources.list
-	echo "deb-src http://deb.debian.org/debian sid main contrib non-free" >> /etc/apt/sources.list
-
-	apt update
-	apt dist-upgrade -y
-
-	echo " "
-	echo -e "=============== OK =============== \n" 
-	read -r -p "Press Enter to continue..."
-
-	echo -e "=============== INSTALL CORE PACKAGES =============== \n" 
-
-	apt install -y cockpit git net-tools wget vim rsync neofetch \
-		screen unrar p7zip vim network-manager-gnome zsh
-
-	systemctl enable NetworkManager.service
-	echo "Set managed=true" >> /etc/NetworkManager/NetworkManager.conf
-	systemctl disable dhcpcd.service
-
-	echo " "
-	echo -e "=============== OK =============== \n" 
-	read -r -p "Press Enter to continue..."
-
-	dialog --msgbox 'The raspi-config app will be open, please change your configurations' 7 50
-
-	raspi-config
 
 }
 
-function newuser {
+function hostnamer {
 
 	clear
-	echo -e "=============== ADD A USER TO A SUDO GROUP =============== \n" 
+	dialog --title "Hostname" \
+    --backtitle "036 Creative Studios" \
+    --inputbox "Please write your hostname (ex: A036-oracle)" 8 80 2>"$HOSTTEMP"
+
+    RESPONSE=$?
+    DATA=$(<$HOSTTEMP)
+
+    case $RESPONSE in
+    0) 
+		hostnamectl set-hostname "${DATA}" 
+		return;;
+    1) 
+        clear; exit 0  
+        return;;
+    255) 
+        clear; exit 0
+        return;;
+    esac
 	
-	read -r -p "Write your new user: " SUDOUSER
-	adduser "$SUDOUSER"
-	usermod -aG sudo victor7w7r
+}
+
+function localer {
+
+	clear
+	dialog --msgbox "America/Guayaquil is the timezone by default, if you want to change, here is the command\n\n \
+		timedatectl set-timezone REGION/CITY" 9 50
+
+	timedatectl set-timezone America/Guayaquil
+
+	dialog --clear --backtitle "036 Creative Studios" \
+		--title "Locale" \
+		--menu "Choose your keyboard layout" 12 50 4 \
+		Spanish "es" \
+		English "us" 2>"${LOCALESTEMP}"
+
+		menuitem=$(<"${LOCALESTEMP}")
+
+		case $menuitem in
+			Spanish) 
+				clear
+				localectl set-keymap es
+				return;;
+			English) 
+				clear
+				localectl set-keymap us
+				return;;
+			*) clear; exit 0;;
+		esac
+}
+
+function cockpit {
+
+	clear
+	echo -e "=============== COCKPIT SERVICE (IP:9090) =============== \n" 
+	
+	systemctl enable --now cockpit.socket
+	systemctl start cockpit.socket
 
 	echo " "
 	echo -e "=============== OK =============== \n" 
 	read -r -p "Press Enter to continue..."
+
 }
 
 function graphical {
 
-	clear
-	echo -e "=============== XFCE =============== \n" 
+	LISTHOME=""
+
+	dialog --title "Graphical" --backtitle "036 Creative Studios" \
+		--yesno "Install XFCE as Desktop Environment?" 7 60
+
+	response=$?
 	
-	apt install xserver-xorg xfce4 xfce4-goodies xfce4-indicator-plugin \
-		blueman ttf-ubuntu-font-family firefox nemo cinnamon-l10n gdm3
+	if [ $response = 0 ]; then
 
-	touch /root/.xinitrc
-	echo 'export XAUTHORITY=${HOME}/.Xauthority' > /root/.xinitrc
-	echo 'xfce4-session' >> /root/.xinitrc	
+	XRDPTOGGLE=1
 
-	touch /home/"$SUDOUSER"/.xinitrc
-	echo 'export XAUTHORITY=${HOME}/.Xauthority' > /home/"$SUDOUSER"/.xinitrc
-	echo 'xfce4-session' >>  /home/"$SUDOUSER"/.xinitrc
+		clear
+		echo -e "=============== EPEL & XFCE =============== \n" 
+		
+		dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm --assumeyes 
+		dnf update --assumeyes 
+		dnf groupinstall "base-x" --assumeyes 
+		dnf groupinstall "xfce" --assumeyes 
+		dnf install xfce4-whiskermenu-plugin --assumeyes 
+		touch .xinitrc
+		echo "xfce4-session" > .xinitrc
 
-	chown "$SUDOUSER" /home/"$SUDOUSER"/.xinitrc
+		LISTHOME=$(ls /home)
+
+		for HOME in $LISTHOME; do
+			touch /home/"$HOME"/.xinitrc
+			echo "xfce4-session" > /home/"$HOME"/.xinitrc
+			chown "$HOME" /home/"$HOME"/.xinitrc
+		done
+
+		echo " "
+		echo -e "=============== OK =============== \n" 
+		read -r -p "Press Enter to continue..."
+
+	else
+
+		clear
+		echo -e "=============== EPEL =============== \n" 
+		
+		dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm --assumeyes 
+	
+		echo " "
+		echo -e "=============== OK =============== \n" 
+		read -r -p "Press Enter to continue..."
+		return
+	fi
+
+}
+
+function drivers {
+
+	clear
+
+	dialog --title "VMware" --backtitle "036 Creative Studios" \
+		--yesno "This is a VMware Guest" 8 60
+
+	clear
+	response=$?
+
+	if [ $response = 0 ]; then
+
+	clear
+	dnf install open-vm-tools open-vm-tools-desktop --assumeyes 
+
+	elif [ $response -eq 1 ]; then
+		clear
+		return
+	else
+		clear
+		return
+	fi
+
+}
+
+function remote {
+
+	clear
+
+	dialog --title "SSH" --backtitle "036 Creative Studios" \
+		--yesno "Permit Root Login?" 8 60
+
+	response=$?
+
+	if [ $response = 0 ]; then
+
+		clear
+
+		echo -e "=============== SSH: PERMIT ROOT LOGIN ===============  \n" 
+
+		sed -i 's/^#PermitRootLogin\s.*$/PermitRootLogin Yes/' \
+			/etc/ssh/sshd_config &> /dev/null
+		systemctl enable sshd
+		systemctl restart sshd
+
+		echo " "
+		echo -e "=============== OK =============== \n" 
+		read -r -p "Press Enter to continue..."
+
+	fi
+
+	clear
+
+	if [ $XRDPTOGGLE -eq 1 ]; then
+
+		echo -e "=============== XRDP ===============  \n" 
+
+		LISTHOME=""
+
+		dnf install xrdp --assumeyes 
+
+		LISTHOME=$(ls /home)
+
+		for HOME in $LISTHOME; do
+			touch /home/"$HOME"/.Xclients
+			echo "xfce4-session" > /home/"$HOME"/.Xclients
+			chmod a+x /home/"$HOME"/.Xclients
+			chown "$HOME" /home/"$HOME"/.Xclients
+		done
+
+		systemctl enable xrdp
+		systemctl enable xrdp-sesman
+		systemctl start xrdp
+		systemctl start xrdp-sesman
+		firewall-cmd --permanent --add-port=3389/tcp 
+		firewall-cmd --reload
+		chcon --type=bin_t /usr/sbin/xrdp
+		chcon --type=bin_t /usr/sbin/xrdp-sesman
+
+		echo " "
+		echo -e "=============== OK =============== \n" 
+		read -r -p "Press Enter to continue..."
+	
+	fi
+
+}
+
+function kvm {
+
+	dialog --title "KVM" --backtitle "036 Creative Studios" \
+		--yesno "Install Oracle Linux KVM Suite?" 8 60
+
+	response=$?
+
+	if [ $response = 0 ]; then
+
+	clear
+
+	echo -e "=============== KVM ===============  \n" 
+
+	dnf config-manager --enable ol8_appstream ol8_kvm_appstream ol8_developer_EPEL
+	dnf module install virt --assumeyes 
+	dnf install virt-install virt-viewer virt-manager edk2-ovmf virt-v2v cockpit-machines --assumeyes
+	virt-host-validate qemu
+	systemctl enable libvirtd
+	systemctl start libvirtd
+	dnf install dnf-plugins-core --assumeyes 
+	dnf config-manager --add-repo https://www.kraxel.org/repos/firmware.repo
+	dnf install edk2.git-ovmf-x64 --assumeyes 
+
+	echo "nvram = [" >> /etc/libvirt/qemu.conf
+	echo "	\"/usr/edk.git/OVMF_CODE.fd:/usr/edk.git/OVMF_VARS.fd\"" >> /etc/libvirt/qemu.conf
+	echo "]" >> /etc/libvirt/qemu.conf
+
+	systemctl restart libvirtd
+	systemctl enable serial-getty@ttyS0.service
+	systemctl start serial-getty@ttyS0.service
 
 	echo " "
 	echo -e "=============== OK =============== \n" 
 	read -r -p "Press Enter to continue..."
+
+	elif [ $response -eq 1 ]; then
+		clear
+		return
+	else
+		clear
+		return
+	fi
 
 }
 
@@ -292,19 +428,23 @@ function ohmyzsh {
 	clear
 	echo -e "=============== OMZ =============== \n" 
 
-	touch /home/"$SUDOUSER"/omz.sh
+	LISTHOME=$(ls /home)
 
-	echo '#!/bin/bash' > /home/"$SUDOUSER"/omz.sh
-	echo 'sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"' >> /home/"$SUDOUSER"/omz.sh
-	echo 'sed -i -e "s/ZSH_THEME=.*/ZSH_THEME=\"pmcgee\"/" .zshrc' >> /home/"$SUDOUSER"/omz.sh
-	echo 'sed -i -e "/^source $ZSH.*/i ZSH_DISABLE_COMPFIX=true" .zshrc' >> /home/"$SUDOUSER"/omz.sh
-	echo 'sudo ln -s "$HOME"/.zshrc /root/.zshrc' >> /home/"$SUDOUSER"/omz.sh
-	echo 'sudo ln -s "$HOME"/.oh-my-zsh /root/.oh-my-zsh' >> /home/"$SUDOUSER"/omz.sh
-	echo 'git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting' >> /home/"$SUDOUSER"/omz.sh
-	echo 'git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions' >> /home/"$SUDOUSER"/omz.sh
-	echo 'sed -i -e "s/plugins=(.*/plugins=(git zsh-syntax-highlighting zsh-autosuggestions)/" .zshrc' >> /home/"$SUDOUSER"/omz.sh
+	for HOME in $LISTHOME; do
 
-	chown "$SUDOUSER" /home/"$SUDOUSER"/omz.sh
+		echo '#!/bin/bash' > /home/"$HOME"/omz.sh
+		echo 'sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"' >> /home/"$HOME"/omz.sh
+		echo 'sed -i -e "s/ZSH_THEME=.*/ZSH_THEME=\"pmcgee\"/" .zshrc' >> /home/"$HOME"/omz.sh
+		echo 'sed -i -e "/^source $ZSH.*/i ZSH_DISABLE_COMPFIX=true" .zshrc' >> /home/"$HOME"/omz.sh
+		echo 'sudo ln -s "$HOME"/.zshrc /root/.zshrc' >> /home/"$HOME"/omz.sh
+		echo 'sudo ln -s "$HOME"/.oh-my-zsh /root/.oh-my-zsh' >> /home/"$HOME"/omz.sh
+		echo 'git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting' >> /home/"$HOME"/omz.sh
+		echo 'git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions' >> /home/"$HOME"/omz.sh
+		echo 'sed -i -e "s/plugins=(.*/plugins=(git zsh-syntax-highlighting zsh-autosuggestions)/" .zshrc' >> /home/"$HOME"/omz.sh
+
+		chown "$HOME" /home/"$HOME"/omz.sh
+
+	done
 
 	echo "We create a script called omz.sh in your home directory, after reboot, use chmod +x at omz.sh"
 
@@ -316,41 +456,34 @@ function ohmyzsh {
 
 function software {
 
-	systemctl mask lvm2-monitor
-
-	echo "disable_overscan=1" >> /boot/config.txt
-	echo "hdmi_drive=2" >> /boot/config.txt
-
-		dialog --title "More Sofware!!" --backtitle "036 Creative Studios" \
+	dialog --title "More Sofware!!" --backtitle "036 Creative Studios" \
 		--yesno "This script has a little pack of software, Do you like it?\n \
 			-> baobab \n \
 			-> ntfs-3g \n \
-			-> exfat-utils \n \
-			-> xrdp \n \
-			-> xarchiver \n \
-			-> synaptic \n \
-			-> neofetch \n \
-			-> vlc \n \
-			-> gdebi \n \
-			-> numix-gtk-theme-git\n \
-			-> numix-icon-theme " 26 65
+			-> gparted \n \
+			-> nautilus \n \
+			-> gedit \n \
+			-> tar \n \
+			-> yum-utils \n \
+			-> numix-gtk-theme \n \
+			-> numix-icon-theme \n \
+			-> numix-icon-theme-circle" 20 65
 	clear
 	response=$?
 
 	if [ $response = 0 ]; then
-
+	
 	clear
 	echo -e "=============== SOFTWARE =============== \n" 
 
-	sudo apt install -y xrdp gdebi synaptic aptitude neofetch vlc libwnck-common libwnck22 \
-		baobab ntfs-3g exfat-fuse exfat-utils xarchiver numix-gtk-theme numix-icon-theme-circle
+	dnf install baobab ntfs-3g gparted exfatprogs nautilus gedit tar yum-utils --assumeyes
 
-	adduser xrdp ssl-cert
-	sudo systemctl enable xrdp
-	sudo systemctl enable xrdp-sesman
-	sudo systemctl enable preload
-	
-
+	dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm --assumeyes
+	dnf install numix-gtk-theme --assumeyes
+	dnf install gnome-icon-theme --assumeyes
+	dnf install numix-icon-theme --assumeyes
+	dnf install numix-icon-theme-circle --assumeyes
+	dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm --assumeyes
 
 	echo " "
 	echo -e "=============== OK =============== \n" 
@@ -362,21 +495,22 @@ function software {
 		return
 	else
 		clear
-		exit 0
+		return
 	fi
+
 }
 
 function finisher {
 
 	clear
-	dialog --msgbox 'READY!!!, Your RPI4 is succesfully configured, if you have errors, please report at 036raspberry in GitHub' 7 50
+	dialog --msgbox 'READY!!!, Your Server is succesfully configured, if you have errors, please report at 036bootstrap in GitHub' 7 50
 	clear
-	echo "Please reboot your rpi4 to make changes"
+	echo "Please reboot yout server to make changes"
 	exit 0
+
 }
 
 core
 
 [ -f $LOCALESTEMP ] && rm $LOCALESTEMP
 [ -f $HOSTTEMP ] && rm $HOSTTEMP
-[ -f $GRAPHICALTEMP ] && rm $GRAPHICALTEMP
