Oracle Linux and Raspios Config tentative release

diff --git a/raspios-config b/raspios-config
--- a/raspios-config
+++ b/raspios-config
@@ -19,7 +19,7 @@ function cleanup { rm $LOCALESTEMP; $HOSTTEMP; $GRAPHICALTEMP exit; }
 
 trap cleanup; SIGHUP SIGINT SIGTERM
 
-function core { clear; cover; sleep 1s; verify; packages; hostnamer; localer; newuser; swapper; graphical; aur; ohmyzsh; software; finisher;}
+function core { clear; cover; sleep 1s; verify; packages; newuser; graphical; ohmyzsh; software; finisher;}
 
 function cover {
 	echo '          					    ``...`                                                    '
@@ -107,13 +107,33 @@ function verify {
         exit 1
     fi
 
-    SELECTOR="pacman"
+    SELECTOR="apt"
 	whichverify "$SELECTOR"
 	local res=$?
 
 	if [ $res -eq 1 ]; then
 		clear
-		echo "ERROR: Arch Linux pacman is not available in this system, this system isn't Arch Linux?"
+		echo "ERROR: APT is not available in this system, this system isn't Debian?"
+		exit 1
+	fi
+
+    SELECTOR="raspi-config"
+	whichverify "$SELECTOR"
+	local res=$?
+
+	if [ $res -eq 1 ]; then
+		clear
+		echo "ERROR: This Debian disto doesn't have a raspi-config app, please use Raspberry Pi OS Lite, exiting"
+		exit 1
+	fi
+
+	SELECTOR="openbox-lxde-session"
+	whichverify "$SELECTOR"
+	local res=$?
+
+	if [ $res -eq 0 ]; then
+		clear
+		echo "ERROR: Ok, is Raspbery Pi OS, but this is not a Raspberry Pi OS Lite, exiting"
 		exit 1
 	fi
 
@@ -125,14 +145,9 @@ function verify {
 		exit 1
 	fi
 
-	echo "Populating Arch ARM Keys.."
+    echo "Updating Debian repositories..."
 
-	pacman-key --init &> /dev/null
-	pacman-key --populate archlinuxarm  &> /dev/null
-
-    echo "Updating Arch ARM Repositories..."
-
-    pacman -Sy &> /dev/null
+    apt update &> /dev/null
 
     SELECTOR="lsb_release"
 	whichverify "$SELECTOR"
@@ -140,12 +155,12 @@ function verify {
 
 	if [ $res -eq 1 ]; then
 		echo "lsb_release is not available in this system, installing"
-		pacman -S lsb-release --noconfirm &> /dev/null
+		apt install -y lsb-release -&> /dev/null
 	fi
 
 	IS_ARCH=$(lsb_release -is)
 
-	if [ "$IS_ARCH" != "Arch" ]; then
+	if [ "$IS_ARCH" != "Debian" ]; then
 		clear
 		echo "ERROR: Your Operating System is not Arch Linux, exiting"
 		exit 1
@@ -157,10 +172,8 @@ function verify {
 
 	if [ $res -eq 1 ]; then
 		echo "dialog is not available in this system, installing"
-		pacman -S dialog --noconfirm &> /dev/null
+		apt install -y dialog &> /dev/null
 	fi
-
-	pacman -S ncurses --noconfirm &> /dev/null
 
 	echo "All dependencies is ok!"
 
@@ -179,16 +192,13 @@ function verify {
 function packages {
 	clear
 
-	echo -e "=============== SYSTEM UPDATE AND INSTALL CORE PACKAGES =============== \n" 
+	sed -i 's/^#PermitRootLogin\s.*$/PermitRootLogin Yes/' \
+	/etc/ssh/sshd_config &> /dev/null
 
-		systemctl enable sshd &> /dev/null
-		systemctl start sshd &> /dev/null
+	echo -e "=============== SYSTEM UPDATE  =============== \n" 
 
-		pacman -Syyu --noconfirm 
-		pacman -S sudo git wget rsync networkmanager neofetch \
-		screen unrar p7zip vim zsh --noconfirm 
+	apt upgrade -y
 		
-
 	echo -e "=============== OK =============== \n" 
 	read -r -p "Press Enter to continue..."
 
@@ -201,71 +211,41 @@ function packages {
 	echo " "
 	echo -e "=============== OK =============== \n" 
 	read -r -p "Press Enter to continue..."
-
-
-}
-
-function hostnamer {
 	
-
 	clear
-	dialog --title "Hostname" \
-    --backtitle "036 Creative Studios" \
-    --inputbox "Please write your hostname (ex: A036-rpi4)" 8 80 2>"$HOSTTEMP"
 
-    RESPONSE=$?
-    DATA=$(<$HOSTTEMP)
+	echo -e "=============== CHANGE TO A SID REPOSITORIES AND DIST UPGRADE =============== \n" 
 
-    case $RESPONSE in
-    0) 
-		echo "${DATA}" > /etc/hostname
-		echo "127.0.1.1        ${DATA}" >> /etc/hosts
-		return;;
-    1) 
-        clear; exit 0  
-        return;;
-    255) 
-        clear; exit 0
-        return;;
-    esac
-}
+	mv /etc/apt/sources.list /etc/apt/sources.list.old
+	mv /etc/apt/sources.list.d /etc/apt/sources.list.d.old
 
-function localer {
+	echo "deb http://deb.debian.org/debian sid main contrib non-free" > /etc/apt/sources.list
+	echo "deb-src http://deb.debian.org/debian sid main contrib non-free" >> /etc/apt/sources.list
 
-	clear
-	dialog --msgbox "America/Guayaquil is the timezone by default, if you want to change, here is the command\n\n \
-		ln -sf /usr/share/zoneinfo/REGION/CITY /etc/localtime" 9 50
+	apt update
+	apt dist-upgrade -y
 
-	ln -sf /usr/share/zoneinfo/America/Guayaquil /etc/localtime
-	hwclock --systohc
+	echo " "
+	echo -e "=============== OK =============== \n" 
+	read -r -p "Press Enter to continue..."
 
-	dialog --clear --backtitle "036 Creative Studios" \
-		--title "Locale" \
-		--menu "Choose your locale, if you want to change to other locales, check the README of the Github of this project" 12 50 4 \
-		Spanish "es_ES" \
-		English "en_US" 2>"${LOCALESTEMP}"
+	echo -e "=============== INSTALL CORE PACKAGES =============== \n" 
 
-		menuitem=$(<"${LOCALESTEMP}")
+	apt install -y cockpit git net-tools wget vim rsync neofetch \
+		screen unrar p7zip vim network-manager-gnome zsh
 
-		case $menuitem in
-			Spanish) 
-				clear
-				sed -i 's/^#es_ES.UTF-8 UTF-8/es_ES.UTF-8 UTF-8/' /etc/locale.gen &> /dev/null
-				locale-gen
-				echo 'LANG="es_ES.UTF-8"' > /etc/locale.conf
-				echo 'LC_TIME="es_ES.UTF-8"' >> /etc/locale.conf
-				echo 'LANGUAGE="es_EC:es_ES:es"' >> /etc/locale.conf
-				return;;
-			English) 
-				clear
-				sed -i 's/^#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen &> /dev/null
-				locale-gen
-				echo 'LANG="en_US.UTF-8"' > /etc/locale.conf
-				echo 'LC_TIME="en_US.UTF-8"' >> /etc/locale.conf
-				echo 'LANGUAGE="es_US:en"' >> /etc/locale.conf
-				return;;
-			*) clear; exit 0;;
-		esac
+	systemctl enable NetworkManager.service
+	echo "Set managed=true" >> /etc/NetworkManager/NetworkManager.conf
+	systemctl disable dhcpcd.service
+
+	echo " "
+	echo -e "=============== OK =============== \n" 
+	read -r -p "Press Enter to continue..."
+
+	dialog --msgbox 'The raspi-config app will be open, please change your configurations' 7 50
+
+	raspi-config
+
 }
 
 function newuser {
@@ -274,30 +254,9 @@ function newuser {
 	echo -e "=============== ADD A USER TO A SUDO GROUP =============== \n" 
 	
 	read -r -p "Write your new user: " SUDOUSER
-	useradd --create-home "$SUDOUSER"
-	passwd "$SUDOUSER"
-	usermod -aG wheel "$SUDOUSER"
-	userdel alarm
-	sed -i 's/^#.*%wheel ALL=(ALL) ALL$/%wheel ALL=(ALL) ALL/' /etc/sudoers &> /dev/null
+	adduser "$SUDOUSER"
+	usermod -aG sudo victor7w7r
 
-	echo " "
-	echo -e "=============== OK =============== \n" 
-	read -r -p "Press Enter to continue..."
-}
-
-function swapper {
-
-	clear
-	echo -e "=============== SWAPPING =============== \n" 
-
-	dd if=/dev/zero of=/swapfile bs=1M count=1024 status=progress
-	chmod 600 /swapfile
-	mkswap /swapfile
-	swapon /swapfile
-	echo "swapfile none swap defaults 0 0" >> /etc/fstab
-	echo "vm.swappiness=1" >> /etc/sysctl.d/99-sysctl.conf
-
-	
 	echo " "
 	echo -e "=============== OK =============== \n" 
 	read -r -p "Press Enter to continue..."
@@ -306,118 +265,20 @@ function swapper {
 function graphical {
 
 	clear
-	dialog --clear --title "Graphical Environment" \
-	--backtitle "036 Creative Studios" \
-	--menu "Choose a GUI, these are the common used, this script recommends XFCE" 15 50 4 \
-			XFCE "Xfce Desktop Environment" \
-			GNOME "GNOME Desktop Environment" \
-			KDE "KDE Desktop Environment" \
-			XORG "Minimal xorg Desktop" \
-			NOGUI "No install GUI" 2>"${GRAPHICALTEMP}"
-
-	menuitem=$(<"${GRAPHICALTEMP}")
-
-		case $menuitem in
-			XFCE) 
-
-				clear
-				echo -e "=============== XFCE =============== \n" 
+	echo -e "=============== XFCE =============== \n" 
 	
-				pacman -S xorg-server xf86-video-fbturbo-git xorg-xinit --noconfirm
-				pacman -S xfce4 gdm xfce4-goodies ttf-ubuntu-font-family gtk-engines gtk-engine-murrine \
-					gnome-themes-standard xdg-user-dirs ttf-dejavu gvfs xfce4-notifyd network-manager-applet volumeicon --noconfirm
-				systemctl enable gdm
+	apt install xserver-xorg xfce4 xfce4-goodies xfce4-indicator-plugin \
+		blueman ttf-ubuntu-font-family firefox nemo cinnamon-l10n gdm3
 
-				touch /HOME/"$SUDOUSER"/.xinitrc
-				echo "export XAUTHORITY=${HOME}/.Xauthority" > /HOME/"$SUDOUSER"/.xinitrc
-				echo "exec dbus-run-session -- startxfce4" >> /HOME/"$SUDOUSER"/.xinitrc	
+	touch /root/.xinitrc
+	echo 'export XAUTHORITY=${HOME}/.Xauthority' > /root/.xinitrc
+	echo 'xfce4-session' >> /root/.xinitrc	
 
-				echo " "
-				echo -e "=============== OK =============== \n" 
-				read -r -p "Press Enter to continue..."
-				return;;
+	touch /home/"$SUDOUSER"/.xinitrc
+	echo 'export XAUTHORITY=${HOME}/.Xauthority' > /home/"$SUDOUSER"/.xinitrc
+	echo 'xfce4-session' >>  /home/"$SUDOUSER"/.xinitrc
 
-			GNOME) 
-
-				clear
-				echo -e "=============== GNOME =============== \n" 
-				pacman -S xorg-server xf86-video-fbturbo-git xorg-xinit --noconfirm
-				pacman -S gnome gdm gnome-themes-standard network-manager-applet --noconfirm
-				systemctl enable gdm
-
-				echo " "
-				echo -e "=============== OK =============== \n" 
-				read -r -p "Press Enter to continue..."
-				return;;
-
-			KDE) 
-
-				clear
-				echo -e "=============== KDE =============== \n" 
-				pacman -S xorg-server xf86-video-fbturbo-git xorg-xinit --noconfirm
-				pacman -S plasma plasma-wayland-session kde-applications network-manager-applet \
-					network-manager-applet volumeicon --noconfirm
-				systemctl enable sddm.service
-
-				echo " "
-				echo -e "=============== OK =============== \n" 
-				read -r -p "Press Enter to continue..."
-				return;;
-
-			XORG) 
-
-				clear
-				echo -e "=============== XORG ONLY =============== \n" 
-				pacman -S xorg-server xf86-video-fbturbo-git xorg-xinit --noconfirm
-
-				echo " "
-				echo -e "=============== OK =============== \n" 
-				read -r -p "Press Enter to continue..."
-				return;;
-
-			NOGUI) 
-				return;;
-
-			*) clear; exit 0;;
-		esac
-
-			clear
-			echo -e "=============== BLUETOOTH AND SOUND =============== \n" 
-
-			pacman -S alsa-utils alsa-firmware alsa-lib alsa-plugins pulseaudio-alsa \
-				pulseaudio-bluetooth bluez-utils libmm-glib modemmanager blueman --noconfirm
-
-			sudo systemctl enable ModemManager
-			sudo systemctl enable bluetooth
-			sudo systemctl start ModemManager
-			sudo systemctl start bluetooth
-
-			echo "enable_uart=1" > /boot/config.txt
-			echo "dtparam=audio=on" >> /boot/config.txt
-			echo "hdmi_drive=2" >> /boot/config.txt
-			echo "audio_pwm_mode=2" >> /boot/config.txt
-			echo "disable_overscan=1" >> /boot/config.txt
-			echo "gpu_mem=64" >> /boot/config.txt
-			echo "cma=512" >> /boot/config.txt
-			echo "dtoverlay=vc4-fkms-v3d" >> /boot/config.txt
-			echo "max_framebuffers=2" >> /boot/config.txt
-
-			echo " "
-			echo -e "=============== OK =============== \n" 
-			read -r -p "Press Enter to continue..."
-
-}
-
-function aur {
-
-	clear
-	echo -e "=============== AUR (YAY ASKS YOU YOUR PASSWORD, PAY ATTENTION) ===============  \n" 
-
-	pacman -S --needed base-devel fakeroot packer go --noconfirm
-
-	sudo -u "$SUDOUSER" bash -c 'cd; git clone https://aur.archlinux.org/yay-bin.git'
-	sudo -u "$SUDOUSER" bash -c 'cd; cd yay-bin; makepkg -si'
-	sudo -u "$SUDOUSER" bash -c 'cd; rm -rf yay-bin'
+	chown "$SUDOUSER" /home/"$SUDOUSER"/.xinitrc
 
 	echo " "
 	echo -e "=============== OK =============== \n" 
@@ -456,51 +317,39 @@ function software {
 
 	systemctl mask lvm2-monitor
 
+	echo "disable_overscan=1" >> /boot/config.txt
+	echo "hdmi_drive=2" >> /boot/config.txt
+
 		dialog --title "More Sofware!!" --backtitle "036 Creative Studios" \
 		--yesno "This script has a little pack of software, Do you like it?\n \
 			-> baobab \n \
 			-> ntfs-3g \n \
-			-> exfatprogs \n \
 			-> exfat-utils \n \
 			-> xrdp \n \
 			-> xarchiver \n \
-			-> xorgxrdp \n \
-			-> xorgxrdp \n \
-			-> visual-studio-code \n \
-			-> rpi-eeprom-git \n \
-			-> rpi-imager \n \
-			-> box64 \n \
+			-> synaptic \n \
+			-> neofetch \n \
+			-> vlc \n \
+			-> gdebi \n \
 			-> numix-gtk-theme-git\n \
-			-> numix-icon-theme \n \
-			-> preload " 26 65
+			-> numix-icon-theme " 26 65
 	clear
 	response=$?
 
 	if [ $response = 0 ]; then
-	
+
 	clear
 	echo -e "=============== SOFTWARE =============== \n" 
 
-	touch /home/"$SUDOUSER"/software.sh
+	sudo apt install -y xrdp gdebi synaptic aptitude neofetch vlc libwnck-common libwnck22 \
+		baobab ntfs-3g exfat-fuse exfat-utils xarchiver numix-gtk-theme numix-icon-theme-circle
 
-	echo allowed_users=anybody > /etc/X11/Xwrapper.config
+	adduser xrdp ssl-cert
+	sudo systemctl enable xrdp
+	sudo systemctl enable xrdp-sesman
+	sudo systemctl enable preload
+	
 
-	echo '!#/bin/bash' > /home/"$SUDOUSER"/software.sh
-	echo 'yay -S baobab ntfs-3g exfatprogs exfat-utils \' >> /home/"$SUDOUSER"/software.sh
-	echo 'xarchiver gparted xrdp \' >> /home/"$SUDOUSER"/software.sh
-	echo 'xorgxrdp pi-bluetooth visual-studio-code-bin preload \' >> /home/"$SUDOUSER"/software.sh
-	echo 'rpi-eeprom-git rpi-imager box64 \' >> /home/"$SUDOUSER"/software.sh
-	echo 'brave-bin exe-thumbnailer github-desktop-bin gobject-introspection libdbusmenu-gtk2 \' >> /home/"$SUDOUSER"/software.sh
-	echo 'libdbusmenu-glib libdbusmenu-gtk3 appmenu-gtk-module numix-gtk-theme \' >> /home/"$SUDOUSER"/software.sh
-	echo 'numix-icon-theme-git numix-circle-icon-theme-git' >> /home/"$SUDOUSER"/software.sh
-
-	echo 'systemctl enable xrdp' >> /home/"$SUDOUSER"/software.sh
-	echo 'systemctl enable xrdp-sesman' >> /home/"$SUDOUSER"/software.sh
-	echo 'systemctl enable preload' >> /home/"$SUDOUSER"/software.sh
-		
-	chown "$SUDOUSER" /home/"$SUDOUSER"/software.sh
-
-	echo "We create a script called software.sh in your home directory, after reboot, use chmod +x at software.sh"
 
 	echo " "
 	echo -e "=============== OK =============== \n" 
@@ -515,7 +364,6 @@ function software {
 		exit 0
 	fi
 }
-
 
 function finisher {
 
